"""add new field for purpose of pet record

Revision ID: 115ba927870e
Revises: 5bfc2a0380a6
Create Date: 2025-05-11 23:46:49.300407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115ba927870e'
down_revision: Union[str, None] = '5bfc2a0380a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('purpose', sa.Enum('ADOPTION', 'LOST_PET', name='purposepet'), nullable=True))
    op.create_index(op.f('ix_pets_purpose'), 'pets', ['purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pets_purpose'), table_name='pets')
    op.drop_column('pets', 'purpose')
    # ### end Alembic commands ###
