"""create adoptions table

Revision ID: 39188b21238a
Revises: 5b5d684c93f8
Create Date: 2025-05-05 05:11:42.121507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39188b21238a'
down_revision: Union[str, None] = '5b5d684c93f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('adopter_id', sa.Integer(), nullable=True),
    sa.Column('adoption_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('agreement_signed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adopter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['adoption_pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoptions_adopter_id'), 'adoptions', ['adopter_id'], unique=False)
    op.create_index(op.f('ix_adoptions_approved_by'), 'adoptions', ['approved_by'], unique=False)
    op.create_index(op.f('ix_adoptions_created_at'), 'adoptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_adoptions_deleted_at'), 'adoptions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_adoptions_updated_at'), 'adoptions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoptions_updated_at'), table_name='adoptions')
    op.drop_index(op.f('ix_adoptions_deleted_at'), table_name='adoptions')
    op.drop_index(op.f('ix_adoptions_created_at'), table_name='adoptions')
    op.drop_index(op.f('ix_adoptions_approved_by'), table_name='adoptions')
    op.drop_index(op.f('ix_adoptions_adopter_id'), table_name='adoptions')
    op.drop_table('adoptions')
    # ### end Alembic commands ###
