"""add image url to pets and lost_pet_reports

Revision ID: 54536a460357
Revises: c54180e9c264
Create Date: 2025-04-22 17:36:21.898753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54536a460357'
down_revision: Union[str, None] = 'c54180e9c264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_pet_reports', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('pets', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'image_url')
    op.drop_column('lost_pet_reports', 'image_url')
    # ### end Alembic commands ###
