"""update nullable fields for user model

Revision ID: 5b5d684c93f8
Revises: 3113045d2e27
Create Date: 2025-05-04 21:37:48.230169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b5d684c93f8'
down_revision: Union[str, None] = 'aba1026a4fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'contact',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('users', 'home_street',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'city',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'home_street',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'contact',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
