"""add new field for  pet model

Revision ID: 5bfc2a0380a6
Revises: 970bd0161774
Create Date: 2025-05-06 12:27:15.735367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfc2a0380a6'
down_revision: Union[str, None] = '970bd0161774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('is_for_adoption', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_pets_is_for_adoption'), 'pets', ['is_for_adoption'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pets_is_for_adoption'), table_name='pets')
    op.drop_column('pets', 'is_for_adoption')
    # ### end Alembic commands ###
