"""update pet model for vaccination

Revision ID: 651c9bb6859c
Revises: e7eab2835aac
Create Date: 2025-05-12 19:18:02.178762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '651c9bb6859c'
down_revision: Union[str, None] = 'e7eab2835aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'purpose',
               existing_type=mysql.ENUM('ADOPTION', 'LOST_PET'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pets', 'purpose',
               existing_type=mysql.ENUM('ADOPTION', 'LOST_PET'),
               nullable=True)
    # ### end Alembic commands ###
