"""remove update delete at default

Revision ID: 8142da93d024
Revises: 825f3af634b7
Create Date: 2025-05-14 13:57:18.572277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8142da93d024'
down_revision: Union[str, None] = '825f3af634b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transfer_coordinations_deleted_at'), 'transfer_coordinations', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_coordinations_deleted_at'), table_name='transfer_coordinations')
    # ### end Alembic commands ###
