"""add_transfer_coordination_table

Revision ID: 825f3af634b7
Revises: fe17b495c6b8
Create Date: 2025-05-14 07:59:18.815454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825f3af634b7'
down_revision: Union[str, None] = 'fe17b495c6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_coordinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barangay_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('request_datetime', sa.DateTime(), nullable=True),
    sa.Column('pet_type', sa.Enum('DOG', 'CAT', name='pettype'), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_coordinations_barangay_name'), 'transfer_coordinations', ['barangay_name'], unique=False)
    op.create_index(op.f('ix_transfer_coordinations_id'), 'transfer_coordinations', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_coordinations_request_datetime'), 'transfer_coordinations', ['request_datetime'], unique=False)
    op.create_index(op.f('ix_transfer_coordinations_status'), 'transfer_coordinations', ['status'], unique=False)
    op.create_index(op.f('ix_transfer_coordinations_user_id'), 'transfer_coordinations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_coordinations_user_id'), table_name='transfer_coordinations')
    op.drop_index(op.f('ix_transfer_coordinations_status'), table_name='transfer_coordinations')
    op.drop_index(op.f('ix_transfer_coordinations_request_datetime'), table_name='transfer_coordinations')
    op.drop_index(op.f('ix_transfer_coordinations_id'), table_name='transfer_coordinations')
    op.drop_index(op.f('ix_transfer_coordinations_barangay_name'), table_name='transfer_coordinations')
    op.drop_table('transfer_coordinations')
    # ### end Alembic commands ###
