"""create lost_pet_report table

Revision ID: 8f33af16d50a
Revises: c75d814881b9
Create Date: 2025-03-08 18:27:28.950727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f33af16d50a'
down_revision: Union[str, None] = 'c75d814881b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_pet_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lost_pet_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('report_location', sa.String(length=255), nullable=False),
    sa.Column('report_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lost_pet_id'], ['lost_pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_pet_reports_created_at'), 'lost_pet_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_lost_pet_reports_deleted_at'), 'lost_pet_reports', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_lost_pet_reports_id'), 'lost_pet_reports', ['id'], unique=False)
    op.create_index(op.f('ix_lost_pet_reports_lost_pet_id'), 'lost_pet_reports', ['lost_pet_id'], unique=False)
    op.create_index(op.f('ix_lost_pet_reports_report_date'), 'lost_pet_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_lost_pet_reports_reporter_id'), 'lost_pet_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_lost_pet_reports_updated_at'), 'lost_pet_reports', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lost_pet_reports_updated_at'), table_name='lost_pet_reports')
    op.drop_index(op.f('ix_lost_pet_reports_reporter_id'), table_name='lost_pet_reports')
    op.drop_index(op.f('ix_lost_pet_reports_report_date'), table_name='lost_pet_reports')
    op.drop_index(op.f('ix_lost_pet_reports_lost_pet_id'), table_name='lost_pet_reports')
    op.drop_index(op.f('ix_lost_pet_reports_id'), table_name='lost_pet_reports')
    op.drop_index(op.f('ix_lost_pet_reports_deleted_at'), table_name='lost_pet_reports')
    op.drop_index(op.f('ix_lost_pet_reports_created_at'), table_name='lost_pet_reports')
    op.drop_table('lost_pet_reports')
    # ### end Alembic commands ###
