"""add schedule field in adoption table

Revision ID: 970bd0161774
Revises: ee8f56c0b286
Create Date: 2025-05-06 00:13:59.884823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970bd0161774'
down_revision: Union[str, None] = 'ee8f56c0b286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoptions', sa.Column('schedule', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adoptions', 'schedule')
    # ### end Alembic commands ###
