"""Add new model for pet adoption records

Revision ID: a6f8e35011c3
Revises: 54536a460357
Create Date: 2025-04-28 22:26:47.620427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f8e35011c3'
down_revision: Union[str, None] = '54536a460357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('found_in', sa.String(length=255), nullable=False),
    sa.Column('additional_details', sa.Text(), nullable=True),
    sa.Column('media', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_pets_created_at'), 'adoption_pets', ['created_at'], unique=False)
    op.create_index(op.f('ix_adoption_pets_deleted_at'), 'adoption_pets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_adoption_pets_id'), 'adoption_pets', ['id'], unique=False)
    op.create_index(op.f('ix_adoption_pets_pet_id'), 'adoption_pets', ['pet_id'], unique=False)
    op.create_index(op.f('ix_adoption_pets_status'), 'adoption_pets', ['status'], unique=False)
    op.create_index(op.f('ix_adoption_pets_updated_at'), 'adoption_pets', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoption_pets_updated_at'), table_name='adoption_pets')
    op.drop_index(op.f('ix_adoption_pets_status'), table_name='adoption_pets')
    op.drop_index(op.f('ix_adoption_pets_pet_id'), table_name='adoption_pets')
    op.drop_index(op.f('ix_adoption_pets_id'), table_name='adoption_pets')
    op.drop_index(op.f('ix_adoption_pets_deleted_at'), table_name='adoption_pets')
    op.drop_index(op.f('ix_adoption_pets_created_at'), table_name='adoption_pets')
    op.drop_table('adoption_pets')
    # ### end Alembic commands ###
