"""added new fields for user model

Revision ID: aba1026a4fa4
Revises: b242fc36e97b
Create Date: 2025-05-04 18:48:34.544230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aba1026a4fa4'
down_revision: Union[str, None] = 'b242fc36e97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('middle_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('contact', sa.String(length=25), nullable=False))
    op.add_column('users', sa.Column('home_street', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('region', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.String(length=4), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_contact'), 'users', ['contact'], unique=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_middle_name'), 'users', ['middle_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_middle_name'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_contact'), table_name='users')
    op.drop_column('users', 'country')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'region')
    op.drop_column('users', 'city')
    op.drop_column('users', 'home_street')
    op.drop_column('users', 'contact')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
