"""add new table for views of pet adoption

Revision ID: b242fc36e97b
Revises: d1c0087c0e2a
Create Date: 2025-04-29 22:11:13.587857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b242fc36e97b'
down_revision: Union[str, None] = 'd1c0087c0e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_pet_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adoption_pet_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('others', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adoption_pet_id'], ['adoption_pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_pet_views_created_at'), 'adoption_pet_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_adoption_pet_views_deleted_at'), 'adoption_pet_views', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_adoption_pet_views_id'), 'adoption_pet_views', ['id'], unique=False)
    op.create_index(op.f('ix_adoption_pet_views_others'), 'adoption_pet_views', ['others'], unique=False)
    op.create_index(op.f('ix_adoption_pet_views_updated_at'), 'adoption_pet_views', ['updated_at'], unique=False)
    op.create_index(op.f('ix_adoption_pet_views_viewed_at'), 'adoption_pet_views', ['viewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoption_pet_views_viewed_at'), table_name='adoption_pet_views')
    op.drop_index(op.f('ix_adoption_pet_views_updated_at'), table_name='adoption_pet_views')
    op.drop_index(op.f('ix_adoption_pet_views_others'), table_name='adoption_pet_views')
    op.drop_index(op.f('ix_adoption_pet_views_id'), table_name='adoption_pet_views')
    op.drop_index(op.f('ix_adoption_pet_views_deleted_at'), table_name='adoption_pet_views')
    op.drop_index(op.f('ix_adoption_pet_views_created_at'), table_name='adoption_pet_views')
    op.drop_table('adoption_pet_views')
    # ### end Alembic commands ###
