"""add field 'deleted_at' and remove 'is_deleted' for pets table

Revision ID: c75d814881b9
Revises: e6a8a5cc3a1d
Create Date: 2025-03-07 21:42:45.305635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c75d814881b9'
down_revision: Union[str, None] = 'e6a8a5cc3a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_column('pets', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('pets', 'deleted_at')
    # ### end Alembic commands ###
