"""add new model for vaccination

Revision ID: dbfc8dfca45b
Revises: d22f36cf5e65
Create Date: 2025-05-12 18:23:57.755246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfc8dfca45b'
down_revision: Union[str, None] = 'd22f36cf5e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccination_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_type', sa.Enum('RABIES', 'DISTEMPER', 'PARVOVIRUS', 'ADENOVIRUS', 'BORDETELLA', 'LEPTOSPIROSIS', 'LYME', 'FELINE_RABIES', 'FELINE_DISTEMPER', 'FELINE_CALICIVIRUS', 'FELINE_HERPESVIRUS', 'FELINE_LEUKEMIA', 'OTHER', name='vaccinetype'), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('administered_date', sa.DateTime(), nullable=False),
    sa.Column('administered_by', sa.String(length=100), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccination_records_contact'), 'vaccination_records', ['contact'], unique=False)
    op.create_index(op.f('ix_vaccination_records_id'), 'vaccination_records', ['id'], unique=False)
    op.create_index(op.f('ix_vaccination_records_owner'), 'vaccination_records', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccination_records_owner'), table_name='vaccination_records')
    op.drop_index(op.f('ix_vaccination_records_id'), table_name='vaccination_records')
    op.drop_index(op.f('ix_vaccination_records_contact'), table_name='vaccination_records')
    op.drop_table('vaccination_records')
    # ### end Alembic commands ###
