"""add_new_vaccination_purpose

Revision ID: e7eab2835aac
Revises: dbfc8dfca45b
Create Date: 2025-05-12 19:02:56.907629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7eab2835aac'
down_revision: Union[str, None] = 'dbfc8dfca45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
