"""update adoption pet field

Revision ID: ee8f56c0b286
Revises: 6f2763192daa
Create Date: 2025-05-05 06:05:06.859710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ee8f56c0b286'
down_revision: Union[str, None] = '6f2763192daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoptions', sa.Column('adoption_pet_id', sa.Integer(), nullable=False))
    op.drop_constraint('adoptions_ibfk_3', 'adoptions', type_='foreignkey')
    op.create_foreign_key(None, 'adoptions', 'adoption_pets', ['adoption_pet_id'], ['id'])
    op.drop_column('adoptions', 'pet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adoptions', sa.Column('pet_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'adoptions', type_='foreignkey')
    op.create_foreign_key('adoptions_ibfk_3', 'adoptions', 'adoption_pets', ['pet_id'], ['id'])
    op.drop_column('adoptions', 'adoption_pet_id')
    # ### end Alembic commands ###
