"""add field for match flagged

Revision ID: fe17b495c6b8
Revises: 77366c7d7ee8
Create Date: 2025-05-14 00:01:24.427999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe17b495c6b8'
down_revision: Union[str, None] = '77366c7d7ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_pet_reports', sa.Column('is_matched', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_lost_pet_reports_is_matched'), 'lost_pet_reports', ['is_matched'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lost_pet_reports_is_matched'), table_name='lost_pet_reports')
    op.drop_column('lost_pet_reports', 'is_matched')
    # ### end Alembic commands ###
